name: jobsofcicd

on: 
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: code
        run: echo "push code"

  build:
  needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "build code"

  test:
   needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "test code"

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "deploy code"
